[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.19.0"       # or "22.12.0"
  NPM_FLAGS = "--legacy-peer-deps"

[build.processing]
  skip_processing = true
