# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.11.1"   # <-- set this to EXACT output of: node -v
  NPM_FLAGS = "--legacy-peer-deps"

# Turn OFF Netlify post-processing. We don't want it touching Sanity's JS bundles.
[build.processing]
  skip_processing = true

# (If your site already has Asset Optimization toggled in the UI, also disable it there)
